
use_frameworks!

target 'ScaledVisibleCellsCollectionView_Example' do
  pod "ScaledVisibleCellsCollectionView", :path => "../"
end

target 'ScaledVisibleCellsCollectionView_Tests' do
  pod "ScaledVisibleCellsCollectionView", :path => "../"
end
